SRC_DIR = source/EventMgr

SRCS = $(wildcard $(SRC_DIR)/*.c)

TARGET_LIB = EventMgr.a

include git/libpalm/makefile.setup
include git/libbse/makefile.setup.so

all: $(OBJ_TARGET_LIB)

include git/libbse/makefile.build
